'use client';
import { useState } from 'react';
const tabs=[['Case inbox','case-inbox.test'],['Corporate registry','cipa-registry.test'],['Sanctions screening','sanctions-screen.test']];
const nav=['Brief','Search','Network','Transactions','Documents','Screening','Evidence','Decision'];
export function InvestigationLab(){const[tab,setTab]=useState(1);const[q,setQ]=useState('Kgale Water');const[evidence,setEvidence]=useState(3);return <main className="app">
  <div className="training">TRAINING SIMULATION — NOT A LIVE SYSTEM · ALL RECORDS ARE FICTIONAL</div>
  <header className="top"><div className="brand">IF</div><div><p className="overline">ICiFF SIMULATION LAB</p><h1>Kgale Water Infrastructure Case</h1></div><div className="stats"><span><b>62%</b> progress</span><span><b>24:18</b> active</span><button>ND</button></div></header>
  <div className="workspace"><aside className="rail"><p>CASEWORK</p>{nav.map((x,i)=><button key={x} className={x==='Search'?'active':''}><i>{String(i+1).padStart(2,'0')}</i>{x}</button>)}<small>● &nbsp; Autosaved</small></aside>
  <section className="browser"><div className="tabbar"><div className="dots">● ● ●</div>{tabs.map((x,i)=><button key={x[1]} onClick={()=>setTab(i)} className={tab===i?'selected':''}>{x[0]} <span>×</span></button>)}<button className="plus">＋</button></div>
  <div className="toolbar"><button>‹</button><button>›</button><button>↻</button><div className="address">◇ &nbsp; https://{tabs[tab][1]}</div><button>☆</button><button>⋮</button></div>
  <div className="portal-alert">BOTSWANA CORPORATE REGISTRY <b>TRAINING PORTAL</b></div><div className="portal-head"><div className="seal">BR</div><div><p>GOVERNMENT SERVICES SIMULATION</p><h2>Botswana Corporate Registry</h2></div><nav>Search　 Services　 Help</nav></div>
  <div className="content"><p className="crumb">Home / Company search / Results</p><div className="searchbox"><div><label>Company name or registration number</label><div><input value={q} onChange={x=>setQ(x.target.value)}/><button>Search registry</button></div></div><button className="filter">Filters <b>2</b></button></div>
  <section className="results"><header><div><p>SEARCH RESULTS</p><h3>3 records found for “{q}”</h3></div><button>Export results</button></header><div className="row heading"><span>Registered entity</span><span>Registration</span><span>Status</span><span>Incorporated</span><span/></div>
  {[['Kgale Waterworks (Pty) Ltd','Private company · Gaborone','BW-2026-01482','Active','12 Feb 2026'],['Kgale Water Solutions','Business name · Tlokweng','BN-2019-77401','Under review','08 Jul 2019'],['Kgalagadi Water Infrastructure','Private company · Lobatse','BW-2023-08911','Active','21 Nov 2023']].map((r,i)=><div className={'row '+(i===0?'focus':'')} key={r[2]}><span><b>{r[0]}</b><small>{r[1]}</small></span><span>{r[2]}</span><span><i className={r[3]==='Active'?'green':'amber'}/>{r[3]}</span><span>{r[4]}</span><span><button>View record →</button></span></div>)}
  <div className="analyst"><b>i</b><p><strong>Analyst note</strong>Compare registration numbers, directors and filing dates with supplier documents.</p><button onClick={()=>setEvidence(evidence+1)}>Save search as evidence</button></div></section></div></section>
  <aside className="evidence"><header><div><p className="overline">EVIDENCE NOTEBOOK</p><h2>{evidence} saved items</h2></div><button>—</button></header><Evidence tag="REGISTRY" title="Director record differs">Registry lists Naledi Tiro as current director; supplier form names Kabelo Moagi.</Evidence><Evidence tag="PAYMENT" title="Beneficiary mismatch">Receiving account is associated with another company in the ownership chain.</Evidence><Evidence tag="DOCUMENT" title="Supplier declaration"/><button className="add">＋ Add investigation note</button><div className="objective"><b>Current objective <span>2 of 4 checks</span></b><p>Verify the supplier’s registered directors and ownership.</p><i><b/></i></div></aside></div></main>}
function Evidence({tag,title,children}:{tag:string,title:string,children?:React.ReactNode}){return <article className="card"><label className={tag.toLowerCase()}>{tag}</label><h3>{title}</h3>{children&&<p>{children}</p>}<small>Saved {tag==='REGISTRY'?4:tag==='PAYMENT'?9:12} min ago</small></article>}
