import { integer, real, sqliteTable, text } from 'drizzle-orm/sqlite-core';

const timestamps = { createdAt: integer('created_at', { mode: 'timestamp' }).notNull(), updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull() };
export const users = sqliteTable('users', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), role: text('role', { enum: ['learner','facilitator','administrator'] }).notNull(), active: integer('active', { mode: 'boolean' }).notNull().default(true), ...timestamps });
export const scenarios = sqliteTable('scenarios', { id: text('id').primaryKey(), slug: text('slug').notNull().unique(), title: text('title').notNull(), description: text('description').notNull(), difficulty: text('difficulty').notNull(), estimatedMinutes: integer('estimated_minutes').notNull(), version: integer('version').notNull().default(1), active: integer('active', { mode: 'boolean' }).notNull().default(true), briefingJson: text('briefing_json').notNull(), scoringConfigJson: text('scoring_config_json').notNull(), ...timestamps });
export const entities = sqliteTable('scenario_entities', { id: text('id').primaryKey(), scenarioId: text('scenario_id').notNull(), entityType: text('entity_type').notNull(), legalName: text('legal_name').notNull(), aliasesJson: text('aliases_json').notNull(), registrationNumber: text('registration_number'), jurisdiction: text('jurisdiction'), status: text('status'), attributesJson: text('attributes_json').notNull(), hiddenTruthJson: text('hidden_truth_json').notNull(), ...timestamps });
export const relationships = sqliteTable('entity_relationships', { id: text('id').primaryKey(), scenarioId: text('scenario_id').notNull(), sourceEntityId: text('source_entity_id').notNull(), targetEntityId: text('target_entity_id').notNull(), relationshipType: text('relationship_type').notNull(), ownershipPercentage: real('ownership_percentage'), sourceReference: text('source_reference'), ...timestamps });
export const attempts = sqliteTable('attempts', { id: text('id').primaryKey(), scenarioId: text('scenario_id').notNull(), learnerId: text('learner_id').notNull(), status: text('status', { enum: ['assigned','in_progress','submitted'] }).notNull(), finalDisposition: text('final_disposition'), riskLevel: text('risk_level'), finalRationale: text('final_rationale'), score: integer('score'), activeSeconds: integer('active_seconds').notNull().default(0), submittedAt: integer('submitted_at', { mode: 'timestamp' }), ...timestamps });
export const evidenceItems = sqliteTable('evidence_items', { id: text('id').primaryKey(), attemptId: text('attempt_id').notNull(), sourceType: text('source_type').notNull(), sourceId: text('source_id').notNull(), category: text('category').notNull(), learnerNote: text('learner_note'), snapshotJson: text('snapshot_json').notNull(), createdAt: integer('created_at', { mode: 'timestamp' }).notNull() });
export const screeningCandidates = sqliteTable('screening_candidates', { id: text('id').primaryKey(), attemptId: text('attempt_id').notNull(), profileName: text('profile_name').notNull(), listType: text('list_type').notNull(), matchScore: integer('match_score').notNull(), explanationJson: text('explanation_json').notNull(), learnerResolution: text('learner_resolution'), learnerRationale: text('learner_rationale'), createdAt: integer('created_at', { mode: 'timestamp' }).notNull() });
export const browserTabs = sqliteTable('browser_tabs', { id: text('id').primaryKey(), attemptId: text('attempt_id').notNull(), portalKey: text('portal_key').notNull(), fictionalUrl: text('fictional_url').notNull(), title: text('title').notNull(), stateJson: text('state_json').notNull(), position: integer('position').notNull(), ...timestamps });
